swagger: '2.0'

info:
  version: "1"
  title: Invencycle API

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /bikes:
    # This is a HTTP operation
    get:
      tags:
       - bikes
      # Describe this verb here. Note: you can use markdown
      description: "Gets bikes, their components, and specifications."
      # This is array of GET operation parameters:
      produces:
        - application/json
      parameters:
        - in: query
          name: make
          description: "Search through bikes by brand."
          required: false
          type: string
        - in: query
          name: model
          description: "Search through bikes by model"
          required: false
          type: string
        - in: query
          name: type
          description: "Search through bikes by type of bike"
          required: false
          type: string
        - in: query
          name: suspension
          description: "Search through bikes by suspension setup (none, hardtail, or full)"
          required: false
          type: string
        # Expected responses for this operation:
      responses:
        # Response code
        "200":
          description: "Successful response"
          schema:
            $ref: "#/definitions/ResultObjects"
        "404":
          description: "Not Found"
          schema:
            $ref: "#/definitions/Error"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/Errors"
    post:
      tags:
      - bikes
      description: "Adds new bikes"
      produces:
        - application/json
      parameters: 
        - name: body
          in: body
          description: "Bike data that will be added to the database."
          required: true
          schema:
            $ref: "#/definitions/Bikes"
      responses:
        "200":
          description: Successful response
        "201":
          description: Resource created
        "204":
          description: No content
        "401":
          description: Unauthorized
        "405":
          description: Invalid input
        "500":
          description: Internal server error


  /bikes/{bikeID}:
    get:
      tags:
        - bikes
      description: "Find bikes by bike ID"
      produces:
        - application/json
      parameters:
        - name: bikeID
          in: path
          description: "Bike ID to be searched by"
          required: true
          type: string
      responses:
        "200":
          description: "Successful response"
          schema:
            $ref: "#/definitions/ResultObject"
        "404":
          description: "Resource not found"
          schema:
            $ref: "#/definitions/Errors"
        "500":
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/Errors"
            
    put:
      tags:
        - bikes
      description: "Change bike or component information, add components, or delete individual components from a bike"
      produces:
        - application/json
      parameters:
        - name: bikeID
          in: path
          description: "Bike ID to be searched by"
          required: true
          type: string
        - name: body
          in: body
          description: "Bike data that should be updated."
          required: true
          schema:
            $ref: "#/definitions/Bikes"
      responses:
        "200":
          description: Successful response
        "201":
          description: Resource created
        "204":
          description: No content
        "401":
          description: Unauthorized
        "405":
          description: Invalid input
        "500":
          description: Internal server error
    
    delete:
      tags:
        - bikes
      description: "Delete an entire bike"
      produces:
        - application/json
      parameters:
        - name: bikeID
          in: path
          description: "Bike ID to be searched by"
          required: true
          type: string
      responses:
        "200":
          description: Successful response
        "204":
          description: No content
        "401":
          description: Unauthorized
        "405":
          description: Invalid input
        "500":
          description: Internal server error
          
definitions:
  Bikes:
    properties:
      attributes:
          $ref: "#/definitions/Attributes" 
        
  ResultObject:
    properties:
      links:
        $ref: "#/definitions/Links"
      data:
        $ref: "#/definitions/ResourceObject"

  ResultObjects:
    properties:
      links:
        $ref: "#/definitions/Links"
      data:
        type: array
        items:
          $ref: "#/definitions/ResourceObject"
        
  ResourceObject:
    properties:
      id:
        type: string
      type:
        type: string
      attributes:
        $ref: "#/definitions/Attributes"
        
  Attributes:
    properties:
      make:
        type: string
      model:
        type: string
      year: 
        type: string
      type: 
        type: string
      frame_size:
        type: string
      msrp:
        type: integer
      front_derailuer_make:
        type: string
      front_derailuer_model:
        type: string
      fork_make:
        type: string
      fork_model:
        type: string
      fork_travel:
        type: integer
      shock_make:
        type: string
      shock_model:
        type: string
      shock_travel:
        type: integer
      front_wheel_make:
        type: string
      front_wheel_model:
        type: string
      front_hub_make:
        type: string
      front_hub_model:
        type: string
      rear_wheel_make:
        type: string
      rear_wheel_model:
        type: string
      rear_hub_make:
        type: string
      rear_hub_model:
        type: string
      front_brake_make:
        type: string
      front_brake_model:
        type: string
      front_rotor_size:
        type: string
      rear_brake_make:
        type: string
      rear_brake_model:
        type: string
      rear_rotor_size:
        type: string

  Links:
      properties:
        self:
          type: string
        first:
          type: string
        last:
          type: string
        prev:
          type: string
        next:
          type: string
  Error:
    type: object
    properties:
      status:
        type: integer
        format: int32
      developerMessage:
        type: string
      userMesage:
        type: string
      code:
        type: integer
      details:
        type: string

  Errors:
    title: ArrayOfErrors
    type: array
    items:
      $ref: "#/definitions/Error"